#!/bin/bash

QEMU_RELEASE=`curl -s https://api.github.com/repos/multiarch/qemu-user-static/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'`

wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_RELEASE}/qemu-arm-static
#wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_RELEASE}/qemu-armeb-static
